version: "2"
services:
  mongo:
    build: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - "./mongo_data:/data/db"
  api:
    build: backend
    ports:
      - 8000:80
    env_file:
      - .env
  front:
    build: front
    ports:
      - 8080:80
      - 8443:443
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/logs:/var/log/nginx:rw"
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - front
