version: "2"
services:
  mongo:
    build: mongo:latest
    env_file:
      - .env
    volumes:
      - "./mongo_data:/data/db"
  api:
    build: backend
    env_file:
      - .env
  front:
    build: front
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/logs:/var/log/nginx:rw"
      - '/etc/letsencrypt/live/biz-alert.ru/fullchain.pem:/certs/fullchain.pem:ro'
      - '/etc/letsencrypt/live/biz-alert.ru/privkey.pem:/certs/privkey.pem:ro'
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - front
